version: "3.8"
services:
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: nginx:stable-alpine
    container_name: panel-front-nginx
    ports:
      - 3000:3000
    volumes:
      - ./configs/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - panel-front-network

networks:
  panel-front-network:
